CREATE SEQUENCE SEQ_JOGADOR START WITH 1 INCREMENT BY 1;

CREATE TABLE JOGADOR (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    POSICAO VARCHAR2(50) NOT NULL,
    NUMERO NUMBER(3) NOT NULL,
    CLUBE VARCHAR2(80) NOT NULL
);
